// Sport name → emoji icon mapping
const SPORT_ICONS = {
  '3x3 Basketball': '\u{1F3C0}',
  'Archery': '\u{1F3F9}',
  'Artistic Gymnastics': '\u{1F938}',
  'Artistic Swimming': '\u{1F6B6}',
  'Athletics (Marathon)': '\u{1F3C3}',
  'Athletics (Race Walk)': '\u{1F6B6}',
  'Athletics (Track & Field)': '\u{1F3C3}',
  'BMX Freestyle': '\u{1F6B2}',
  'BMX Racing': '\u{1F6B2}',
  'Badminton': '\u{1F3F8}',
  'Baseball': '\u26BE',
  'Basketball': '\u{1F3C0}',
  'Beach Volleyball': '\u{1F3D0}',
  'Boxing - Final Stages': '\u{1F94A}',
  'Boxing - Preliminary Stages': '\u{1F94A}',
  'Canoe Slalom': '\u{1F6F6}',
  'Canoe Sprint': '\u{1F6F6}',
  'Climbing': '\u{1F9D7}',
  'Cricket': '\u{1F3CF}',
  'Cycling Road (Road Race)': '\u{1F6B4}',
  'Cycling Road (Time Trial)': '\u{1F6B4}',
  'Cycling Track': '\u{1F6B4}',
  'Diving': '\u{1F3CA}',
  'Equestrian': '\u{1F3C7}',
  'Fencing': '\u{1F93A}',
  'Flag Football': '\u{1F3C8}',
  'Football (Soccer)': '\u26BD',
  'Golf': '\u26F3',
  'Handball': '\u{1F93E}',
  'Hockey': '\u{1F3D1}',
  'Judo': '\u{1F94B}',
  'Lacrosse': '\u{1F94D}',
  'Modern Pentathlon': '\u{1F3BD}',
  'Mountain Bike': '\u{1F6B5}',
  'Open Water Swimming': '\u{1F3CA}',
  'Rhythmic Gymnastics': '\u{1F938}',
  'Rowing': '\u{1F6A3}',
  'Rowing Coastal Beach Sprints': '\u{1F6A3}',
  'Rugby Sevens': '\u{1F3C9}',
  'Sailing (Dinghy, Skiff &\nMultihull)': '\u26F5',
  'Sailing (Windsurfing & Kite)': '\u26F5',
  'Shooting (Rifle & Pistol)': '\u{1F3AF}',
  'Shooting (Shotgun)': '\u{1F3AF}',
  'Skateboarding (Park)': '\u{1F6F9}',
  'Skateboarding (Street)': '\u{1F6F9}',
  'Softball': '\u{1F94E}',
  'Squash': '\u{1F3BE}',
  'Surfing': '\u{1F3C4}',
  'Swimming': '\u{1F3CA}',
  'Table Tennis': '\u{1F3D3}',
  'Taekwondo': '\u{1F94B}',
  'Tennis': '\u{1F3BE}',
  'Trampoline Gymnastics': '\u{1F938}',
  'Triathlon': '\u{1F3CA}',
  'Volleyball': '\u{1F3D0}',
  'Water Polo': '\u{1F93D}',
  'Weightlifting': '\u{1F3CB}',
  'Wrestling': '\u{1F93C}',
};

export function getSportIcon(sport) {
  return SPORT_ICONS[sport] || '\u{1F3C5}'; // default: medal
}
